# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[profile.dev]
rpath = true
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false

[dependencies]
glob = "*"
regex = "*"
regex_macros = "*"
log = "*"
env_logger = "*"
hoedown = "*"
rustc-serialize = "*"
# handlebars = "*"
docopt = "*"
toml = "*"
# notify = "*"
libc = "*"
time = "*"
# iron = "*"
# static = "*"
# mount = "*"
threadpool = "*"
tempdir = "*"
num_cpus = "*"

[dependencies.notify]
path = "../rsnotify"

# [dependencies.rustc-serialize]
# path = "../rustc-serialize"

# [dependencies.hoedown]
# path = "../hoedown"

[dependencies.handlebars]
path = "../handlebars-rust"

[dependencies.anymap]
path = "../anymap"
# git = "https://github.com/chris-morgan/anymap.git"
# branch = "clone"

# [dependencies.iron]
# git = "https://github.com/iron/iron.git"

# [dependencies.toml]
# git = "https://github.com/alexcrichton/toml-rs"

