# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[lib]
name = "diecast"
path = "src/lib/diecast.rs"
plugin = true

[[bin]]
name = "diecast"
doc = false

[profile.dev]
opt-level = 0
debug = true
rpath = true

[dependencies]
glob = "*"

[dependencies.anymap]
git = "https://github.com/chris-morgan/anymap.git"
branch = "clone"

