# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[profile.dev]
rpath = true
# opt-level = 3
# debug = false
# lto = false
# debug-assertions = false

[dependencies]
glob = "*"
regex = "*"
log = "*"
env_logger = "*"
hoedown = "*"
rustc-serialize = "*"
docopt = "*"
toml = "*"
notify = "*"
libc = "*"
time = "*"
threadpool = "*"
tempdir = "*"
num_cpus = "*"
iron = "*"
staticfile = "*"
mount = "*"
chrono = "*"

# for templates
handlebars = "*"

# for renderer
zmq = "*"

# for ws
websocket = "*"

# for git
git2 = "*"

# typemap = "*"

# for rss
rss = "*"

[dependencies.typemap]
path = "../../rust-typemap"
