# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[profile.dev]
opt-level = 0
debug = true
rpath = true

[dependencies]
glob = "*"
regex = "*"
regex_macros = "*"
log = "*"
env_logger = "*"
hoedown = "*"
# handlebars = "*"
rustc-serialize = "*"
docopt = "*"
toml = "*"
notify = "*"
threadpool = "*"
# iron = "*"
# static = "*"
# mount = "*"

# [dependencies.rustc-serialize]
# path = "../rustc-serialize"

# [dependencies.hoedown]
# path = "../hoedown"

[dependencies.handlebars]
path = "../handlebars-rust"

[dependencies.anymap]
path = "../anymap"
# git = "https://github.com/chris-morgan/anymap.git"
# branch = "clone"

# [dependencies.iron]
# git = "https://github.com/iron/iron.git"

# [dependencies.toml]
# git = "https://github.com/alexcrichton/toml-rs"

