# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[profile.dev]
rpath = true
# opt-level = 3
# debug = false
# lto = false
# debug-assertions = false

[dependencies]
glob = "*"
regex = "*"
log = "*"
docopt = "*"
walker = "*"

toml = "*"
time = "*"
threadpool = "*"
tempdir = "*"
num_cpus = "*"
iron = "*"
mount = "*"
typemap = "*"
rustc-serialize = "*"

# for date
chrono = "*"

# unstable
notify = "*"

[dependencies.staticfile]
path = "../../staticfile"
